### ISSUE TITLE
Task to re-compile on file change

### ISSUE THREAD

**Issue by dorianamouroux** [TheThingsNetwork/ttn-stylebook#4]
It would be nice to have a task to recompile the `src` into `dist` folder when you change anything in `src`.

To make it faster, maybe we create different tasks for each pre-processor.

`npm run watch for_less`  
`npm run watch for_sass`  
`npm run watch for_styl`

**Comment by FokkeZB** [comment]
https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/#watch
